config/routes.rb
Rails.application.routes.draw do
  resources :individuals
  resources :timezones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "individuals#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/individual.rb
class Individual < ApplicationRecord
end

app/models/timezone.rb
class Timezone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def timezones
    @timezones = Timezone.order(id: :asc).all
    @timezone_names = @timezones.pluck(:name)
  end

end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :set_individual, only: %i[ show edit update destroy ]

  # GET /individuals or /individuals.json
  def index
    @individuals = Individual.all
  end

  # GET /individuals/1 or /individuals/1.json
  def show
  end

  # GET /individuals/new
  def new
    @individual = Individual.new
    timezones
puts @timezones.size
  end

  # GET /individuals/1/edit
  def edit
    timezones
  end

  # POST /individuals or /individuals.json
  def create
    @individual = Individual.new(individual_params)

    respond_to do |format|
      if @individual.save
        format.html { redirect_to individual_url(@individual), notice: "Individual was successfully created." }
        format.json { render :show, status: :created, location: @individual }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individuals/1 or /individuals/1.json
  def update
    respond_to do |format|
      if @individual.update(individual_params)
        format.html { redirect_to individual_url(@individual), notice: "Individual was successfully updated." }
        format.json { render :show, status: :ok, location: @individual }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1 or /individuals/1.json
  def destroy
    @individual.destroy

    respond_to do |format|
      format.html { redirect_to individuals_url, notice: "Individual was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individual
      @individual = Individual.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def individual_params
      params.require(:individual).permit(:name, :tz)
    end
end

app/controllers/timezones_controller.rb
class TimezonesController < ApplicationController
  before_action :set_timezone, only: %i[ show edit update destroy ]

  # GET /timezones or /timezones.json
  def index
    @timezones = Timezone.all
  end

  # GET /timezones/1 or /timezones/1.json
  def show
  end

  # GET /timezones/new
  def new
    @timezone = Timezone.new
  end

  # GET /timezones/1/edit
  def edit
  end

  # POST /timezones or /timezones.json
  def create
    @timezone = Timezone.new(timezone_params)

    respond_to do |format|
      if @timezone.save
        format.html { redirect_to timezone_url(@timezone), notice: "Timezone was successfully created." }
        format.json { render :show, status: :created, location: @timezone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timezone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timezones/1 or /timezones/1.json
  def update
    respond_to do |format|
      if @timezone.update(timezone_params)
        format.html { redirect_to timezone_url(@timezone), notice: "Timezone was successfully updated." }
        format.json { render :show, status: :ok, location: @timezone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timezone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timezones/1 or /timezones/1.json
  def destroy
    @timezone.destroy

    respond_to do |format|
      format.html { redirect_to timezones_url, notice: "Timezone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timezone
      @timezone = Timezone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timezone_params
      params.require(:timezone).permit(:utc_offset, :is_dst, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/helpers/timezones_helper.rb
module TimezonesHelper
end

app/views/individuals/_form.html.erb
<%= form_with(model: individual) do |form| %>
  <% if individual.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
        <% individual.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :tz, style: "display: block" %>
    <%= form.text_field :tz %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/individuals/_individual.html.erb
<div id="<%= dom_id individual %>">
  <p>
    <strong>Name:</strong>
    <%= individual.name %>
  </p>

  <p>
    <strong>Tz:</strong>
    <%= individual.tz %>
  </p>

</div>

app/views/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render "form", individual: @individual %>

<br>

<div>
  <%= link_to "Show this individual", @individual %> |
  <%= link_to "Back to individuals", individuals_path %>
</div>

app/views/individuals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Individuals</h1>

<div id="individuals">
  <% @individuals.each do |individual| %>
    <%= render individual %>
    <p>
      <%= link_to "Show this individual", individual %>
    </p>
  <% end %>
</div>

<%= link_to "New individual", new_individual_path %>

app/views/individuals/new.html.erb
<h1>New individual</h1>

<%= render "form", individual: @individual %>

<br>

<div>
  <%= link_to "Back to individuals", individuals_path %>
</div>

<%= javascript_tag do %>
  window.addEventListener('turbo:load', function () {
    var item1 = new autoComplete({
        selector: '#individual_tz',
        minChars: 2,
        source: function(term, suggest){
            term = term.toLowerCase();
            var choices = <%= raw @timezone_names %>;
            var suggestions = [];
            for (i=0;i<choices.length;i++)
                if (~choices[i].toLowerCase().indexOf(term)) suggestions.push(choices[i]);
            suggest(suggestions);
        }
    });
    alert("It's loaded!")
  })
<% end %>

app/views/individuals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @individual %>

<div>
  <%= link_to "Edit this individual", edit_individual_path(@individual) %> |
  <%= link_to "Back to individuals", individuals_path %>

  <%= button_to "Destroy this individual", @individual, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timezones/_form.html.erb
<%= form_with(model: timezone) do |form| %>
  <% if timezone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(timezone.errors.count, "error") %> prohibited this timezone from being saved:</h2>

      <ul>
        <% timezone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :utc_offset, style: "display: block" %>
    <%= form.text_field :utc_offset %>
  </div>

  <div>
    <%= form.label :is_dst, style: "display: block" %>
    <%= form.check_box :is_dst %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/timezones/_timezone.html.erb
<div id="<%= dom_id timezone %>">
  <p>
    <strong>Utc offset:</strong>
    <%= timezone.utc_offset %>
  </p>

  <p>
    <strong>Is dst:</strong>
    <%= timezone.is_dst %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= timezone.name %>
  </p>

</div>

app/views/timezones/edit.html.erb
<h1>Editing timezone</h1>

<%= render "form", timezone: @timezone %>

<br>

<div>
  <%= link_to "Show this timezone", @timezone %> |
  <%= link_to "Back to timezones", timezones_path %>
</div>

app/views/timezones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Timezones</h1>

<div id="timezones">
  <% @timezones.each do |timezone| %>
    <%= render timezone %>
    <p>
      <%= link_to "Show this timezone", timezone %>
    </p>
  <% end %>
</div>

<%= link_to "New timezone", new_timezone_path %>

app/views/timezones/new.html.erb
<h1>New timezone</h1>

<%= render "form", timezone: @timezone %>

<br>

<div>
  <%= link_to "Back to timezones", timezones_path %>
</div>

app/views/timezones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @timezone %>

<div>
  <%= link_to "Edit this timezone", edit_timezone_path(@timezone) %> |
  <%= link_to "Back to timezones", timezones_path %>

  <%= button_to "Destroy this timezone", @timezone, method: :delete %>
</div>